version: '3.8'
services:
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    env_file:
      - .env.local
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - mongo-data:/data/db 
    networks:
      - internal-network

  next-insights:
    build:
      context: .
      args:
        - MONGODB_URI=${MONGODB_URI}
    restart: always 
    depends_on:
      - mongodb
    networks:
      - internal-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-insights.rule=Host(`insightsarticle.in`)"
      - "traefik.http.routers.next-insights.entrypoints=websecure"
      - "traefik.http.routers.next-insights.tls.certresolver=myresolver"
      - "traefik.http.services.next-insights.loadbalancer.server.port=3000"
    env_file:
      - .env.local

networks:
  internal-network:
    driver: bridge
  proxy:
    external: true

volumes:
  mongo-data: